const requiredRadioGroups=['screener','rating_mismatch_experience','mismatch_direction','one_scene_rating','rating_trust','extra_context_useful','attention_check','recent_rating_match'];
const requiredCheckboxGroups=['mismatch_causes','helpful_tags'];
const form=document.getElementById('surveyForm'),progressFill=document.getElementById('progressFill'),progressPct=document.getElementById('progressPct'),progressLabel=document.getElementById('progressLabel'),submitBtn=document.getElementById('submitBtn'),disqualifyMsg=document.getElementById('disqualifyMsg'),modal=document.getElementById('thankYouModal'),closeModalBtn=document.getElementById('closeModalBtn');
function selected(n){return form.querySelector('input[name="'+n+'"]:checked')}function checkedCount(n){return form.querySelectorAll('input[name="'+n+'"]:checked').length}
function updateSelectedStyles(n){form.querySelectorAll('input[name="'+n+'"]').forEach(i=>{const l=i.closest('label');if(l)l.classList.toggle('selected',i.checked)})}
function updateProgress(){let a=0;requiredRadioGroups.forEach(n=>{if(selected(n))a++});requiredCheckboxGroups.forEach(n=>{if(checkedCount(n)>0)a++});const t=requiredRadioGroups.length+requiredCheckboxGroups.length,p=Math.round(a/t*100);progressFill.style.width=p+'%';progressPct.textContent=p+'% complete';progressLabel.textContent=p===0?'Not started':p===100?'Ready to submit':'In progress';document.querySelector('.progress-track')?.setAttribute('aria-valuenow',String(p))}
form.querySelectorAll('input[type="radio"],input[type="checkbox"]').forEach(i=>{i.addEventListener('change',()=>{updateSelectedStyles(i.name);i.closest('.q')?.classList.remove('has-error');if(i.name==='screener'){const no=i.value==='no'&&i.checked;disqualifyMsg.style.display=no?'block':'none';submitBtn.disabled=no}updateProgress()})});
function validate(){let valid=true,first=null;requiredRadioGroups.forEach(n=>{const inp=form.querySelector('input[name="'+n+'"]'),q=inp?.closest('.q');if(!selected(n)){valid=false;if(q){q.classList.add('has-error');if(!first)first=q}}else q?.classList.remove('has-error')});requiredCheckboxGroups.forEach(n=>{const inp=form.querySelector('input[name="'+n+'"]'),q=inp?.closest('.q');if(checkedCount(n)===0){valid=false;if(q){q.classList.add('has-error');if(!first)first=q}}else q?.classList.remove('has-error')});return{valid,first}}
function openModal(){modal.classList.add('show');modal.setAttribute('aria-hidden','false');closeModalBtn.focus()}function closeModal(){modal.classList.remove('show');modal.setAttribute('aria-hidden','true')}closeModalBtn.addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('show'))closeModal()});
form.addEventListener('submit',async e=>{e.preventDefault();if(selected('screener')?.value==='no'){disqualifyMsg.style.display='block';document.getElementById('q-screener').scrollIntoView({behavior:'smooth',block:'center'});return}const r=validate();if(!r.valid){r.first.scrollIntoView({behavior:'smooth',block:'center'});return}document.getElementById('timestampField').value=new Date().toISOString();document.getElementById('attentionCheckField').value=String(selected('attention_check')?.value==='agree');submitBtn.disabled=true;submitBtn.textContent='Submitting...';try{const res=await fetch(form.action,{method:form.method,body:new FormData(form),headers:{Accept:'application/json'}});if(res.ok){form.reset();form.querySelectorAll('.selected').forEach(el=>el.classList.remove('selected'));updateProgress();window.scrollTo({top:0,behavior:'smooth'});openModal()}else alert('Submission failed. Please try again.')}catch(err){alert('Submission failed. Please check your connection and try again.')}finally{submitBtn.disabled=false;submitBtn.textContent='Send my gut check'}});
updateProgress();