const requiredRadioGroups=['watched_movie_12mo','anchor_rating_remembered','rating_known_before','expected_intensity','actual_intensity','rating_preparedness','misalignment_direction','trust_impact','overall_rating_trust','extra_context_useful','response_confidence','attention_check'];
const requiredCheckboxGroups=['misalignment_drivers','desired_context_tags'];
const form=document.getElementById('surveyForm');
const progressFill=document.getElementById('progressFill');
const progressPct=document.getElementById('progressPct');
const progressLabel=document.getElementById('progressLabel');
const submitBtn=document.getElementById('submitBtn');
const disqualifyMsg=document.getElementById('disqualifyMsg');
const modal=document.getElementById('thankYouModal');
const closeModalBtn=document.getElementById('closeModalBtn');
function selected(name){return form.querySelector('input[name="'+name+'"]:checked')}
function checkedCount(name){return form.querySelectorAll('input[name="'+name+'"]:checked').length}
function intensityValue(value){if(!value||value==='no_expectation')return null;const num=parseInt(value.charAt(0),10);return Number.isNaN(num)?null:num}
function updateHiddenFields(){const expected=intensityValue(selected('expected_intensity')?.value);const actual=intensityValue(selected('actual_intensity')?.value);document.getElementById('intensity_gap').value=(expected!==null&&actual!==null)?String(actual-expected):'';document.getElementById('attention_check_passed').value=String(selected('attention_check')?.value==='agree');const qualified=selected('watched_movie_12mo')?.value==='yes'&&selected('attention_check')?.value==='agree';document.getElementById('qualified_response').value=String(qualified)}
function updateSelectedStyles(name){form.querySelectorAll('input[name="'+name+'"]').forEach(input=>{const label=input.closest('label');if(label)label.classList.toggle('selected',input.checked)})}
function updateProgress(){let answered=0;requiredRadioGroups.forEach(name=>{if(selected(name))answered++});requiredCheckboxGroups.forEach(name=>{if(checkedCount(name)>0)answered++});const total=requiredRadioGroups.length+requiredCheckboxGroups.length;const pct=Math.round((answered/total)*100);progressFill.style.width=pct+'%';progressPct.textContent=pct+'% complete';progressLabel.textContent=pct===0?'Not started':pct===100?'Ready to submit':'In progress';document.querySelector('.progress-track')?.setAttribute('aria-valuenow',String(pct));updateHiddenFields()}
form.querySelectorAll('input[type="radio"],input[type="checkbox"]').forEach(input=>{input.addEventListener('change',()=>{updateSelectedStyles(input.name);input.closest('.q')?.classList.remove('has-error');if(input.name==='watched_movie_12mo'){const no=input.value==='no'&&input.checked;disqualifyMsg.style.display=no?'block':'none';submitBtn.disabled=no}updateProgress()})});
function validate(){let valid=true;let first=null;requiredRadioGroups.forEach(name=>{const input=form.querySelector('input[name="'+name+'"]');const q=input?.closest('.q');if(!selected(name)){valid=false;if(q){q.classList.add('has-error');if(!first)first=q}}else if(q){q.classList.remove('has-error')}});requiredCheckboxGroups.forEach(name=>{const input=form.querySelector('input[name="'+name+'"]');const q=input?.closest('.q');if(checkedCount(name)===0){valid=false;if(q){q.classList.add('has-error');if(!first)first=q}}else if(q){q.classList.remove('has-error')}});return{valid,first}}
function openModal(){modal.classList.add('show');modal.setAttribute('aria-hidden','false');closeModalBtn.focus()}
function closeModal(){modal.classList.remove('show');modal.setAttribute('aria-hidden','true')}
closeModalBtn.addEventListener('click',closeModal);modal.addEventListener('click',event=>{if(event.target===modal)closeModal()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&modal.classList.contains('show'))closeModal()});
form.addEventListener('submit',async event=>{event.preventDefault();if(selected('watched_movie_12mo')?.value==='no'){disqualifyMsg.style.display='block';document.getElementById('q-watched').scrollIntoView({behavior:'smooth',block:'center'});return}const result=validate();if(!result.valid){result.first.scrollIntoView({behavior:'smooth',block:'center'});return}document.getElementById('submission_timestamp').value=new Date().toISOString();updateHiddenFields();submitBtn.disabled=true;submitBtn.textContent='Submitting...';try{const response=await fetch(form.action,{method:form.method,body:new FormData(form),headers:{Accept:'application/json'}});if(response.ok){form.reset();form.querySelectorAll('.selected').forEach(el=>el.classList.remove('selected'));disqualifyMsg.style.display='none';updateProgress();window.scrollTo({top:0,behavior:'smooth'});openModal()}else{alert('Submission failed. Please try again.')}}catch(error){alert('Submission failed. Please check your connection and try again.')}finally{submitBtn.disabled=false;submitBtn.textContent='Submit my response'}});
updateProgress();
